plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.les24.control'
    compileSdk 37

    defaultConfig {
        applicationId 'ru.les24.control'
        minSdk 23
        targetSdk 37
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.github.mik3y:usb-serial-for-android:3.9.0'
}
